# Generated by Django 4.2.4 on 2023-09-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_sold_user_solditem_sold_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='sold',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
