# Generated by Django 4.2.4 on 2023-09-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_sold_quantity_alter_sold_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='status',
            field=models.CharField(default='In Process', max_length=10),
        ),
    ]
